version: "2"
services:
  db:
    image: mysql:5.6
    environment:
     - MYSQL_ROOT_PASSWORD=toto
     - MYSQL_DATABASE=glpi
     - MYSQL_USER=glpi_user
     - MYSQL_PASSWORD=glpi_pass
    volumes:
     - ...
    networks:
     - ...
  fpm-servers:
    #image: eesprit/glpi-backend:0.90.4
    build: glpi-backend
    volumes:
     - ...
    networks:
     - ...
  frontend:
    #image: eesprit/glpi-frontend:0.90.4
    build: glpi-frontend
    ports:
     - "8001:80"
    volumes:
     - ...
    networks:
     - ...
networks:
  ...

volumes:
  ...
